rules:
  dicom_tags: 
    - tag:  [0x0010,0x0010]
      name: Patient's Name
    - tag:  [0x0010,0x0020]
      name: Patient ID
    - tag:  [0x0010,0x0030]
      name: Patient's Birth Date
    - tag:  [0x0010,0x0030]
      name: Patient's Sex
    - tag:  [0x0010,0x1010]
      name: Patient's Age
    - tag:  [0x0010,0x1020]
      name: Patient's Size
    - tag:  [0x0010,0x1030]
      name: Patient's Weight
    - tag:  [0x0010,0x1040]
      name: Patient's Address
    - tag:  [0x0010,0x1050]
      name: Patient's Telephone Numbers
    - tag:  [0x0010,0x1060]
      name: Patient's Insurance Plan
    - tag:  [0x0010,0x1070]
      name: Patient's Relationship Status
    - tag:  [0x0010,0x1000]
      name: Other Patient IDs
    - tag:  [0x0010,0x1001] 
      name: Other Patient Names  
    - tag:  [0x0010,0x1090] 
      name: Medical Record Locator
    - tag:  [0x0020,0x000D]
      name: Study Instance UID
    - tag:  [0x0020,0x0010]
      name: Study ID
    - tag:  [0x0008,0x0020] 
      name: Study Date
    - tag:  [0x0008,0x0030]
      name: Study Time
    - tag:  [0x0008,0x0090]
      name: Referring Physician's Name
    - tag:  [0x0008,0x0050]
      name: Accession Number
    - tag:  [0x0008,0x1030]
      name: Study Description
    - tag:  [0x0008,0x1048]
      name: Physician(s) of Record
    - tag:  [0x0008,0x1060]
      name: Name of Physician(s) Reading Study
    - tag:  [0x0020,0x000E]
      name: Series Instance UID
    - tag:  [0x0020,0x0011]
      name: Series Number
    - tag:  [0x0008,0x0021]
      name: Series Date
    - tag:  [0x0008,0x0031]
      name: Series Time
    - tag:  [0x0008,0x103E]
      name: Series Description
    - tag:  [0x0008,0x0070]
      name: Manufacturer
    - tag:  [0x0008,0x0080]
      name: Institution Name
    - tag:  [0x0008,0x1010]
      name: Station Name
    - tag:  [0x0008,0x1040]
      name: Institutional Department Name
    - tag:  [0x0008,0x1090]
      name: Manufacturer's Model Name
    - tag:  [0x0018,0x1000]
      name: Device Serial Number
    - tag:  [0x0018,0x1016]
      name: Secondary Capture Device Manufacturer
    - tag:  [0x0018,0x1000]
      name: Device Serial Number
    - tag:  [0x0018,0x1016]
      name: Secondary Capture Device Manufacturer
    - tag:  [0x0018,0x1018]
      name: Secondary Capture Device Manufacturer's Model Name
    - tag:  [0x0008,0x0018]
      name: SOP Instance UID
    - tag:  [0x0020,0x0052]
      name: Frame of Reference UID
    - tag:  [0x0020,0x0200]
      name: Synchronization Frame of Reference UID
    - tag:  [0x0008,0x0081]
      name: Institution Address
    - tag:  [0x0038,0x0010]
      name: Admission ID
    - tag:  [0x0038,0x0061]
      name: Discharge Diagnosis Description
    - tag:  [0x0038,0x0300]
      name: Current Patient Location
    - tag:  [0x0040,0x0001]
      name: Scheduled Station AE Title
    - tag:  [0x0040,0x0002]
      name: Scheduled Procedure Step Start Date
    - tag:  [0x0040,0x0003]
      name: Scheduled Procedure Step Start Time
    - tag:  [0x0040,0x0006]
      name: Scheduled Performing Physician's Name
    - tag:  [0x0040,0x0010]
      name: Scheduled Station Name
    - tag:  [0x0040,0x1001]
      name: Requested Procedure ID
    - tag:  [0x0040,0x1002]
      name: Reason for the Requested Procedure
    - tag:  [0x0040,0x2001]
      name: Reason for the Imaging Service Request
    - tag:  [0x0008,0x1084]
      name: Admitting Diagnoses Description
    - tag:  [0x0008,0x1120]
      name: Referenced Patient Sequence
    - tag:  [0x0010,0x21B0]
      name: Additional Patient History
    - tag:  [0x0038,0x0040]
      name: Discharge Diagnosis Description
    - tag:  [0x0040,0x0241]
      name: Performed Station AE Title
    - tag:  [0x0040,0x0242]
      name: Performed Station Name
    - tag:  [0x0040,0x0243]
      name: Performed Location
    - tag:  [0x0040,0x0244]
      name: Performed Procedure Step Start Date
    - tag:  [0x0040,0x0245]
      name: Performed Procedure Step Start Time
    - tag:  [0x0040,0x0253]
      name: Performed Procedure Step ID
    - tag:  [0x0008,0x002a]
      name: Acquisition DateTime
    - tag:  [0x0008,0x0022]
      name: Acquisition Date
    - tag:  [0x0008,0x0023]
      name: Acquisition Time
    - tag:  [0x0008,0x0024]
      name: Overlay Date
    - tag:  [0x0008,0x0025]
      name: Curve Date
    - tag:  [0x0008,0x0026]
      name: Overlay Time
    - tag:  [0x0008,0x0027]
      name: Curve Time
    - tag:  [0x0013,0x1013]
      name: Private tag data
    - tag:  [0x0008,0x0023]
      name: Content Date
    - tag:  [0x0008,0x0033]
      name: Content Time    
    - tag:  [0x0013,0x1013]
      Name: Private tag data
    - tag:  [0x0008,0x0023] 
      name: Additional Patient History
    - tag:  [0x0008,0x0094]
      name: Referring Physician's Telephone Numbers
  # detect PHI info in DICOM metadata by element name
  keywords:
    - 'Address'
    - 'Telephone Numbers'
    - 'Fax Numbers'
    - 'Address'
  # patterns to detect PHI info in DICOM pixel data
  regex: 
    # - (?!.*[\d:;,])[A-Z][a-z]+(?:[ '-][A-Z][a-z]+|\.[A-Z])*[a-z]* #human name
    - '[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}' #email
    - \d{3}-\d{2}-\d{4} # SSN
    - d{2}/\d{2}/\d{4}  # Date (MM/DD/YYYY)
    - \d{2}.\d{2}.\d{4}  # Date (MM.DD.YYYY)
    - \d{2}-\d{2}-\d{4} # Date (DD-MM-YYYY)
    - \d{2}/\d{2}/\d{2} # Date (MM/DD/YY)
    - \d{2}.\d{2}.\d{2}  # Date (MM.DD.YY)
    - \d{2}-\d{2}-\d{2}  # Date (DD-MM-YY)
    - \d{3}[-.\s]?d{7}  # Phone Number
    - \d{3}[-.\s]?\d{3}[-.\s]?\d{4}  # Phone Number
    - \(\d{3}\)[\s]?\d{3}-\d{4}  # Phone Number
    - \d{5}(?:[-\s]\d{4})?  # Zip Code
    - \d{3}-\d{2}-\d{4}  # Driver's License, Insurance Policy Number, Medical Record Number, Health Insurance Card Number
  # confidence threshold for detecting PHI info in DICOM metadata and for extract text from pixel data
  confidence_threshold: 80